### ISSUE TITLE
Allow testing with newer jquery version

### ISSUE THREAD

**Issue by henrjk** [mmikowski/spa#1]
Forum message [Node nodeunit.js to error( "jQuery requires a window with a document" )](http://www.manning-sandbox.com/message.jspa?messageID=152647) is about an issue when running the tests described in appendix B with a newer jquery version. 

The book errata and the forum post suggest to use older jquery and nodeunit versions as follows:

``` bash
sudo npm install -g jquery@1.8.3
sudo npm install -g nodeunit@0.8.0
```

This issue is about code changes to allow using a current jquery version instead. 

I will provide a pull request for these changes sometimes soon.

**Comment by henrjk** [comment]
The jquery and nodeunit versions which npm installed yesterday are jquery 2.1.1 and nodeunit 0.9.0.

After some debugging and peeking into the jquery sources I found [jquery issue 14549](http://bugs.jquery.com/ticket/14549). 

The `require('jquery')` call now requires a window and window.document object with at least some DOM capabilities. Apparently older jquery versions had lesser needs during the require call or provided these capabilities themselves.

However [jsdom](https://github.com/tmpvar/jsdom) can be used to provide the window and document objects as needed:

``` javascript
var jsdom = require('jsdom').jsdom;
var doc = jsdom(undefined /* markup */, undefined /*options*/ );
window = doc.parentWindow;
// window is  used by require('jsquery'):
require( 'jquery' );
```

The code above requires to have jsdom installed. For example in an `nvm` environment this can be installed as follows (without sudo):

``` bash
npm install -g jsdom
```

This installed jsdom version 1.2.1 for me.

**Comment by henrjk** [comment]
The code needed can be written as a one liner:

``` Javascript
window = require("jsdom").jsdom().parentWindow;
```

**Comment by mmikowski** [comment]
Hi henrjk:

I very much appreciate this pull request.  I propose, however, that we don't change the current listings, as it can break the existing code.  I'd rather fix the file manifest to specify the correct versions.

Instead, I'd like to create a "updates" branch or similar that has these forward-looking changes.  What do you think?  I could also note in the README the purpose of this branch versus the Master branch.

Cheers, Mike

**Comment by henrjk** [comment]
Hey Mike,
This makes perfect sense to me. 
I'd like to thank you for writing this superbly written and insightful book.

Greetings, Henrich
